### ISSUE TITLE
Incorrect dependency in v0.15.0

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/pygeoapi-feedstock#11]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The conda-forge package still includes `future-annotations` as a dependency of this package.  However, it has been dropped as a dependency from the [Github repo](https://github.com/geopython/pygeoapi/blob/0.15.0/requirements.txt) as of v0.15.0.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by ocefpaf** [comment]
Do you want to send a PR to fix it?
